// kong-dice.js
// -----------------------------------------------------------------------------
// Standalone, zero-build frontend for Kong Climb (2_4_kong_climb) — a Stake-style
// dice game. It replays the REAL generated math (the published lookup tables),
// not a client-side formula.
//
// Canonical dice modes: over_NN / under_NN, where NN is the integer slider target.
//   under_NN wins if the roll < NN   -> winChance = NN%
//   over_NN  wins if the roll > NN   -> winChance = (100 - NN)%
// over and under are NOT mirrors: at the same target they have different win
// chances (except NN=50).
//
// Runs in two modes, auto-detected from the launch URL (same pattern as
// games/3_2_mystery_box_cash_paradise/frontend_demo/app.js):
//   LIVE RGS  -> rgs_url + sessionID present: /wallet/authenticate -> /wallet/play
//                -> /wallet/end-round.
//   LOCAL     -> otherwise: weighted-picks an outcome from the mode's lookup table
//                (kong_dice_rgs.json, generated by build_demo_data.py) and builds
//                the SAME round shape the RGS returns. Fully offline.
//
// Every Kong lookup table has uniform weight 1 and exactly two payouts (0 or the
// win value), so a weighted pick + synthesized diceResult/finalWin events
// reproduces the real book exactly.
// -----------------------------------------------------------------------------

const API_MULTIPLIER = 1_000_000; // RGS money: integer, 6 decimals (1_000_000 == 1.0)
const EVENT_SCALE = 100; // payoutMultiplier / event amounts are base-bet x100 (194 == 1.94x)
const LOCAL_START_BALANCE = 1000;
const DATA_URL = "./kong_dice_rgs.json";

// Shared dice-value -> tower-height mapping (% of the game-stage). Used by the
// ape, the right-side marks, the winning-zone shading and the roll animation, so
// everything lives on one 0-100 scale. v=0 -> 8%, v=100 -> 80%.
const AXIS_BOTTOM = 8;
const AXIS_SPAN = 72;
const clampV = (v) => Math.max(0, Math.min(100, v));
const heightPct = (v) => AXIS_BOTTOM + (clampV(v) / 100) * AXIS_SPAN;

// ---- query params -----------------------------------------------------------
const getParam = (k) => new URLSearchParams(window.location.search).get(k);
const RGS_URL = getParam("rgs_url");
const SESSION_ID = getParam("sessionID");
const LANG = getParam("lang") || getParam("language") || "en";
const CURRENCY = getParam("currency") || "USD";
const LAUNCH_MODE = getParam("mode"); // e.g. over_50 (optional)
const IS_LIVE = Boolean(RGS_URL && SESSION_ID);

// ---- currency formatting (from docs/rgs_docs/RGS.md) ------------------------
const CURRENCY_META = {
  USD: { symbol: "$", decimals: 2 }, CAD: { symbol: "CA$", decimals: 2 },
  JPY: { symbol: "¥", decimals: 0 }, EUR: { symbol: "€", decimals: 2 },
  GBP: { symbol: "£", decimals: 2 }, RUB: { symbol: "₽", decimals: 2 },
  CNY: { symbol: "CN¥", decimals: 2 }, PHP: { symbol: "₱", decimals: 2 },
  INR: { symbol: "₹", decimals: 2 }, IDR: { symbol: "Rp", decimals: 0 },
  KRW: { symbol: "₩", decimals: 0 }, BRL: { symbol: "R$", decimals: 2 },
  MXN: { symbol: "MX$", decimals: 2 }, TRY: { symbol: "₺", decimals: 2 },
  XGC: { symbol: "GC", decimals: 2 }, XSC: { symbol: "SC", decimals: 2 },
};
function fmtMoney(amount, currency = state.currency) {
  const m = CURRENCY_META[currency] ?? { symbol: currency, decimals: 2, symbolAfter: true };
  const s = Number(amount).toFixed(m.decimals);
  return m.symbolAfter ? `${s} ${m.symbol}` : `${m.symbol}${s}`;
}

// ---- DOM --------------------------------------------------------------------
const el = (id) => document.getElementById(id);
const ui = {
  chanceSlider: el("chanceSlider"), chanceLabel: el("chanceLabel"),
  targetText: el("targetText"), multiplier: el("multiplier"),
  underBtn: el("underBtn"), overBtn: el("overBtn"),
  betAmount: el("betAmount"), rollBtn: el("rollBtn"),
  betMinus: el("betMinus"), betPlus: el("betPlus"),
  statMultiplier: el("statMultiplier"), statChance: el("statChance"),
  statPayout: el("statPayout"), balanceText: el("balanceText"),
  balanceHudValue: el("balanceHudValue"),
  toast: el("toast"), monkey: el("monkey"),
  modeBadge: el("modeBadge"), roundJson: el("roundJson"), winZone: el("winZone"),
  history: el("history"),
  ruler: el("ruler"), rulerTicks: el("rulerTicks"), rulerFill: el("rulerFill"),
  targetMarker: el("targetMarker"), resultMarker: el("resultMarker"),
  stage: document.querySelector(".game-stage"),
  manualTab: el("manualTab"), autoTab: el("autoTab"),
  manualPanel: el("manualPanel"), autoPanel: el("autoPanel"),
  autoBets: el("autoBets"), autoInfinite: el("autoInfinite"),
  autoWinReset: el("autoWinReset"), autoWinInc: el("autoWinInc"), autoWinPct: el("autoWinPct"),
  autoWinField: el("autoWinField"), autoWinMinus: el("autoWinMinus"), autoWinPlus: el("autoWinPlus"),
  autoLossReset: el("autoLossReset"), autoLossInc: el("autoLossInc"), autoLossPct: el("autoLossPct"),
  autoLossField: el("autoLossField"), autoLossMinus: el("autoLossMinus"), autoLossPlus: el("autoLossPlus"),
  autoStopProfit: el("autoStopProfit"), autoStopLoss: el("autoStopLoss"),
  autoBetsMinus: el("autoBetsMinus"), autoBetsPlus: el("autoBetsPlus"),
  autoStopProfitMinus: el("autoStopProfitMinus"), autoStopProfitPlus: el("autoStopProfitPlus"),
  autoStopLossMinus: el("autoStopLossMinus"), autoStopLossPlus: el("autoStopLossPlus"),
  autoFast: el("autoFast"), autoBtn: el("autoBtn"),
};
// Faint building wash tint per direction (matches the --dir accent).
const DIR_RGB = { under: "255,93,108", over: "53,224,138" };
const els = ui;
const MAX_HISTORY = 8; // recent-results pills kept in the strip

// ---- state ------------------------------------------------------------------
const state = {
  direction: "under",
  target: 50, // slider NN
  balanceApi: 0,
  currency: CURRENCY,
  bet: API_MULTIPLIER,
  rolling: false,
  hasOpenRound: false,
  modesByName: {},
  ranges: { under: { min: 2, max: 97 }, over: { min: 3, max: 98 } },
  betLevels: null,
  auto: {
    running: false, stopRequested: false,
    baseBetApi: 0, workingBetApi: 0,
    betsTarget: 0, betsDone: 0, infinite: false,
    onWin: { mode: "reset", pct: 0 }, onLoss: { mode: "reset", pct: 0 },
    stopProfitApi: 0, stopLossApi: 0, profitApi: 0, fast: false,
  },
};

// ---- money helpers ----------------------------------------------------------
const toUnits = (api) => api / API_MULTIPLIER;
const toApi = (units) => Math.round(units * API_MULTIPLIER);
const betUnits = () => toUnits(state.bet);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---- bet steppers -----------------------------------------------------------
const MIN_BET_UNITS = 0.1; // matches #betAmount min

// Magnitude-aware step so − / + feel right across scales (flat 0.10 is tedious).
function stepFor(v) {
  if (v < 1) return 0.1;
  if (v < 10) return 0.5;
  if (v < 100) return 1;
  if (v < 1000) return 10;
  return 100;
}

// Apply a change to the bet, clamp to [min, balance], snap to live bet levels,
// then reuse the existing #betAmount input handler via a synthetic event.
function nudgeBet(kind) {
  const cur = parseFloat(ui.betAmount.value) || 0;
  let v = cur;
  if (kind === "minus") v = cur - stepFor(cur);
  else if (kind === "plus") v = cur + stepFor(cur);
  else if (kind === "half") v = cur / 2;
  else if (kind === "double") v = cur * 2;

  v = Math.max(MIN_BET_UNITS, v);
  const balUnits = toUnits(state.balanceApi);
  if (balUnits >= MIN_BET_UNITS) v = Math.min(v, balUnits);
  // Live mode: snap to the RGS's published bet levels (reuses snapLiveBet).
  if (IS_LIVE && state.betLevels) v = toUnits(snapLiveBet(toApi(v)));

  ui.betAmount.value = v.toFixed(2);
  ui.betAmount.dispatchEvent(new Event("input", { bubbles: true }));
}

// Number of bets: integer, min 1, step 1.
function nudgeAutoBets(dir) {
  const cur = parseInt(ui.autoBets.value, 10) || 1;
  ui.autoBets.value = String(Math.max(1, cur + dir));
  ui.autoBets.dispatchEvent(new Event("input", { bubbles: true }));
}

// Stop-on-profit / stop-on-loss: currency amount, magnitude-aware step; an empty
// field means "Off", and stepping down through 0 returns it to Off.
function nudgeStop(input, dir) {
  const raw = (input.value || "").trim();
  const cur = raw === "" ? 0 : (parseFloat(raw) || 0);
  const step = cur < 10 ? 1 : cur < 100 ? 5 : cur < 1000 ? 10 : 100;
  const v = cur + dir * step;
  input.value = v <= 0 ? "" : v.toFixed(2);
  input.dispatchEvent(new Event("input", { bubbles: true }));
}

function setBalanceApi(api) {
  state.balanceApi = api;
  ui.balanceText.textContent = "Balance " + fmtMoney(toUnits(api));
  if (ui.balanceHudValue) ui.balanceHudValue.textContent = fmtMoney(toUnits(api));
}

// ---- mode helpers -----------------------------------------------------------
const pad2 = (n) => String(n).padStart(2, "0");
const modeName = (direction, nn) => `${direction}_${pad2(nn)}`;

function clampTarget(direction, nn) {
  const r = state.ranges[direction];
  return Math.max(r.min, Math.min(r.max, Math.round(nn)));
}
function currentMode() {
  return state.modesByName[modeName(state.direction, clampTarget(state.direction, state.target))];
}

// =============================================================================
// LIVE RGS client
// =============================================================================
async function rgsCall(endpoint, body) {
  const res = await fetch(`https://${RGS_URL}${endpoint}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok || json?.statusCode) {
    throw new Error(json?.statusCode || json?.error || `HTTP ${res.status}`);
  }
  return json;
}
const liveAuth = () => rgsCall("/wallet/authenticate", { sessionID: SESSION_ID, language: LANG });
const livePlay = () =>
  rgsCall("/wallet/play", {
    sessionID: SESSION_ID,
    mode: currentMode().name,
    currency: state.currency,
    amount: snapLiveBet(state.bet),
  });
const liveEndRound = () => rgsCall("/wallet/end-round", { sessionID: SESSION_ID });

function snapLiveBet(api) {
  const cfg = state.betLevels;
  if (!cfg) return api;
  if (Array.isArray(cfg.betLevels) && cfg.betLevels.length) {
    return cfg.betLevels.reduce((a, b) => (Math.abs(b - api) < Math.abs(a - api) ? b : a));
  }
  let v = api;
  if (cfg.stepBet) v = Math.round(v / cfg.stepBet) * cfg.stepBet;
  if (cfg.minBet) v = Math.max(cfg.minBet, v);
  if (cfg.maxBet) v = Math.min(cfg.maxBet, v);
  return v;
}

// =============================================================================
// LOCAL — weighted pick over the mode's lookup table, same round shape as /play
// =============================================================================
function pickOutcome(mode) {
  const total = mode.outcomes.reduce((s, o) => s + o.weight, 0);
  let r = Math.random() * total;
  for (const o of mode.outcomes) {
    r -= o.weight;
    if (r < 0) return o;
  }
  return mode.outcomes[mode.outcomes.length - 1];
}

function buildDiceEvents(mode, outcome) {
  const isWin = outcome.payoutCents > 0;
  return [
    {
      index: 0,
      type: "diceResult",
      direction: mode.direction,
      target: mode.target,
      winChance: mode.winChance,
      isWin,
      payoutMultiplier: Math.round(mode.multiplier * EVENT_SCALE),
    },
    { index: 1, type: "finalWin", amount: isWin ? outcome.payoutCents : 0 },
  ];
}

function localAuth() {
  state.balanceApi = toApi(LOCAL_START_BALANCE);
  return {
    balance: { amount: state.balanceApi, currency: state.currency },
    config: { defaultBetLevel: API_MULTIPLIER, betLevels: null },
    round: null,
  };
}

function localPlay() {
  const mode = currentMode();
  state.balanceApi -= state.bet; // debit the bet

  const outcome = pickOutcome(mode);
  const events = buildDiceEvents(mode, outcome);
  const payoutMultiplier = outcome.payoutCents;
  const winApi = Math.round(betUnits() * (payoutMultiplier / EVENT_SCALE) * API_MULTIPLIER);
  state.balanceApi += winApi; // credit (settled immediately, active:false)

  return {
    round: {
      betID: Math.floor(Math.random() * 1e9),
      amount: state.bet,
      payout: winApi,
      payoutMultiplier,
      active: false,
      mode: mode.name,
      state: events,
    },
    balance: { amount: state.balanceApi, currency: state.currency },
  };
}

// =============================================================================
// Event replay — one render path for both LIVE and LOCAL rounds
// =============================================================================
// The rolled number is cosmetic (books store none) — synthesize one consistent
// with the book's win/lose so the ape lands inside/outside the green zone.
function syntheticRoll(mode, isWin) {
  const t = mode.target;
  const rand = (lo, hi) => lo + Math.random() * (hi - lo);
  if (mode.direction === "under") return isWin ? rand(0, t) : rand(t, 100); // under wins roll < target
  return isWin ? rand(t, 100) : rand(0, t); // over wins roll > target
}

async function playEvents(events, fast = false) {
  const ordered = [...events].sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
  const dice = ordered.find((e) => e.type === "diceResult") || {};
  const fin = ordered.find((e) => e.type === "finalWin") || { amount: 0 };
  const isWin = Boolean(dice.isWin);
  const mode = currentMode();

  const roll = syntheticRoll(mode, isWin);
  els.monkey.style.bottom = heightPct(roll) + "%";
  showResult(roll, isWin);
  await sleep(fast ? 90 : 650);

  const betCurrency = betUnits();
  const winMultiplier = (fin.amount || 0) / EVENT_SCALE;
  const payoutCurrency = winMultiplier * betCurrency;
  showToast(
    isWin
      ? `Rolled ${roll.toFixed(2)} — WIN +${fmtMoney(payoutCurrency - betCurrency)}`
      : `Rolled ${roll.toFixed(2)} — LOSS -${fmtMoney(betCurrency)}`,
    isWin ? "win" : "loss"
  );

  // Append this bet's multiplier to the recent-results strip.
  pushHistory((dice.payoutMultiplier || 0) / EVENT_SCALE, isWin);
  return { isWin, netUnits: payoutCurrency - betCurrency };
}

// Add one pill (bet multiplier, coloured by outcome) to the history strip.
function pushHistory(multiplier, isWin) {
  if (!ui.history) return;
  const pill = document.createElement("span");
  pill.className = "hist-pill " + (isWin ? "win" : "loss") + " enter";
  pill.textContent = multiplier.toFixed(2);
  ui.history.appendChild(pill);
  while (ui.history.children.length > MAX_HISTORY) ui.history.removeChild(ui.history.firstChild);
  pill.addEventListener("animationend", () => pill.classList.remove("enter"), { once: true });
}

function showToast(text, kind = "") {
  ui.toast.textContent = text;
  ui.toast.className = "toast show" + (kind ? " " + kind : "");
  setTimeout(() => ui.toast.classList.remove("show"), 1800);
}

// ---- main action ------------------------------------------------------------
// Returns a tagged result so the autobet loop can read the outcome. Manual
// clicks ignore the return value — their behaviour is unchanged.
async function rollDice({ fast = false } = {}) {
  if (state.rolling) return { status: "busy" };
  if (!Number.isFinite(betUnits()) || betUnits() <= 0) {
    showToast("Enter a valid bet amount");
    return { status: "invalid" };
  }
  if (state.bet > state.balanceApi) {
    showToast("Insufficient balance");
    return { status: "insufficient" };
  }

  state.rolling = true;
  ui.rollBtn.disabled = true;
  ui.rollBtn.textContent = "ROLLING...";

  try {
    if (IS_LIVE && state.hasOpenRound) await finalizeRound();

    const resp = IS_LIVE ? await livePlay() : localPlay();
    if (ui.roundJson) ui.roundJson.textContent = JSON.stringify(resp.round, null, 2);
    if (resp.balance) setBalanceApi(resp.balance.amount);

    const round = resp.round || {};
    const events = round.state ?? round.events ?? [];
    if (!events.length) throw new Error("No events in round");

    if (!fast) await sleep(200);
    const played = await playEvents(events, fast);

    if (IS_LIVE && round.active === true) {
      state.hasOpenRound = true;
      await finalizeRound();
    }
    // net = gross payout − stake, in API integer units (works LOCAL + LIVE).
    const netApi = (round.payout ?? 0) - (round.amount ?? state.bet);
    return { status: "ok", isWin: played?.isWin ?? false, netApi };
  } catch (err) {
    console.error(err);
    showToast(rgsErrorMessage(err.message), "loss");
    return { status: "error", message: err.message };
  } finally {
    state.rolling = false;
    if (!state.auto.running) {
      ui.rollBtn.disabled = false;
      ui.rollBtn.textContent = "ROLL DICE";
      setTimeout(updateUI, fast ? 120 : 900); // return the ape to the target line
    }
  }
}

async function finalizeRound() {
  const resp = await liveEndRound();
  if (resp.balance) setBalanceApi(resp.balance.amount);
  state.hasOpenRound = false;
}

// ---- autobet ----------------------------------------------------------------
const AUTO_DELAY = 1000; // normal inter-roll pace (>= the 900ms settle)

function setAutoTab(auto) {
  if (state.auto.running) return; // locked mid-run
  ui.manualTab.classList.toggle("active", !auto);
  ui.autoTab.classList.toggle("active", auto);
  ui.manualPanel.hidden = auto;
  ui.autoPanel.hidden = !auto;
}

// Lock the bet/direction/config inputs during a run (the STOP button stays live).
function lockControls(locked) {
  [
    ui.chanceSlider, ui.betAmount, ui.underBtn, ui.overBtn,
    ui.betMinus, ui.betPlus,
    ui.manualTab, ui.autoTab, ui.autoBets, ui.autoBetsMinus, ui.autoBetsPlus, ui.autoInfinite,
    ui.autoWinReset, ui.autoWinInc, ui.autoWinPct, ui.autoWinMinus, ui.autoWinPlus,
    ui.autoLossReset, ui.autoLossInc, ui.autoLossPct, ui.autoLossMinus, ui.autoLossPlus,
    ui.autoStopProfit, ui.autoStopProfitMinus, ui.autoStopProfitPlus,
    ui.autoStopLoss, ui.autoStopLossMinus, ui.autoStopLossPlus, ui.autoFast,
  ].forEach((n) => { if (n) n.disabled = locked; });
}

function readAutoConfig() {
  const a = state.auto;
  a.infinite = ui.autoInfinite.classList.contains("active");
  a.betsTarget = Math.max(1, parseInt(ui.autoBets.value, 10) || 1);
  a.onWin = { mode: ui.autoWinInc.classList.contains("active") ? "increase" : "reset", pct: Number(ui.autoWinPct.value) || 0 };
  a.onLoss = { mode: ui.autoLossInc.classList.contains("active") ? "increase" : "reset", pct: Number(ui.autoLossPct.value) || 0 };
  a.stopProfitApi = ui.autoStopProfit.value ? toApi(Math.max(0, Number(ui.autoStopProfit.value))) : 0;
  a.stopLossApi = ui.autoStopLoss.value ? toApi(Math.max(0, Number(ui.autoStopLoss.value))) : 0;
  a.fast = ui.autoFast.classList.contains("active");
}

function adjustWorkingBet(isWin) {
  const a = state.auto;
  const rule = isWin ? a.onWin : a.onLoss;
  if (rule.mode === "reset") {
    a.workingBetApi = a.baseBetApi;
  } else {
    a.workingBetApi = Math.max(toApi(0.1), Math.round(a.workingBetApi * (1 + rule.pct / 100)));
    if (IS_LIVE) a.workingBetApi = snapLiveBet(a.workingBetApi);
  }
}

function startAutobet() {
  const a = state.auto;
  if (a.running || state.rolling) { showToast("Finish the current roll first"); return; }
  readAutoConfig();
  a.baseBetApi = a.workingBetApi = state.bet;
  a.betsDone = 0;
  a.profitApi = 0;
  a.stopRequested = false;
  a.running = true;
  lockControls(true);
  ui.autoBtn.textContent = "STOP AUTOBET";
  ui.autoBtn.classList.add("running");
  runAutobet();
}

async function runAutobet() {
  const a = state.auto;
  while (a.running) {
    if (a.stopRequested) break;
    if (!a.infinite && a.betsDone >= a.betsTarget) break;

    state.bet = a.workingBetApi;
    ui.betAmount.value = betUnits().toFixed(2);
    updateUI();
    if (state.bet > state.balanceApi) {
      showToast("Autobet stopped: insufficient balance", "loss");
      break;
    }

    const r = await rollDice({ fast: a.fast });
    if (!r || r.status !== "ok") break;

    a.betsDone++;
    a.profitApi += r.netApi;
    adjustWorkingBet(r.isWin);

    if (a.stopProfitApi > 0 && a.profitApi >= a.stopProfitApi) break;
    if (a.stopLossApi > 0 && a.profitApi <= -a.stopLossApi) break;
    if (a.stopRequested) break;

    await sleep(a.fast ? 60 : AUTO_DELAY);
  }
  stopAutobet();
}

function stopAutobet() {
  const a = state.auto;
  if (!a.running) return;
  a.running = false;
  a.stopRequested = true;
  lockControls(false);
  ui.autoBtn.textContent = "START AUTOBET";
  ui.autoBtn.classList.remove("running");
  // restore the base bet and a clean render.
  state.bet = a.baseBetApi || state.bet;
  ui.betAmount.value = betUnits().toFixed(2);
  ui.rollBtn.disabled = false;
  ui.rollBtn.textContent = "ROLL DICE";
  updateUI();
  const net = toUnits(a.profitApi);
  showToast(`Autobet: ${a.betsDone} rolls, ${net >= 0 ? "+" : "-"}${fmtMoney(Math.abs(net))}`, net >= 0 ? "win" : "loss");
}

function rgsErrorMessage(code) {
  const map = {
    ERR_IS: "Invalid or expired session.", ERR_IPB: "Insufficient balance.",
    ERR_VAL: "Invalid request.", ERR_ATE: "Authentication failed.",
    ERR_GLE: "Gambling limit exceeded.", ERR_LOC: "Invalid player location.",
    ERR_GEN: "Server error, try again.", ERR_MAINTENANCE: "RGS under maintenance.",
  };
  return map[code] || `Error: ${code}`;
}

// ---- UI ---------------------------------------------------------------------
// Paint the green winning band: under wins the [0, target) low band, over wins
// the (target, 100] high band. Positioned on the same axis as the ape and marks.
function paintWinZone(mode) {
  if (!ui.winZone) return;
  const c = DIR_RGB[mode.direction];
  ui.winZone.style.background = `linear-gradient(180deg, rgba(${c},.10), rgba(${c},.03))`;
  if (mode.direction === "under") {
    ui.winZone.style.bottom = heightPct(0) + "%";
    ui.winZone.style.height = (heightPct(mode.target) - heightPct(0)) + "%";
  } else {
    ui.winZone.style.bottom = heightPct(mode.target) + "%";
    ui.winZone.style.height = (heightPct(100) - heightPct(mode.target)) + "%";
  }
}

// Ruler: inside it, bottom:v% == dice value v (0 at bottom, 100 at top).
function buildRuler() {
  if (!ui.rulerTicks || ui.rulerTicks.childElementCount) return;
  const frag = document.createDocumentFragment();
  for (let v = 0; v <= 100; v += 5) {
    const major = v % 25 === 0;
    const tick = document.createElement("div");
    tick.className = "ruler-tick " + (major ? "major" : "minor");
    tick.dataset.v = v;
    tick.style.bottom = v + "%";
    if (major) {
      const lbl = document.createElement("span");
      lbl.className = "lbl";
      lbl.textContent = v;
      tick.appendChild(lbl);
    }
    frag.appendChild(tick);
  }
  ui.rulerTicks.appendChild(frag);
}

// Green target marker + green winning-side segment (flips for over/under).
function paintRuler(mode) {
  if (ui.targetMarker) {
    ui.targetMarker.style.bottom = mode.target + "%";
    ui.targetMarker.querySelector(".val").textContent = mode.target;
  }
  // The green marker replaces the scale label it sits on (avoid a double number).
  if (ui.rulerTicks) {
    ui.rulerTicks.querySelectorAll(".ruler-tick .lbl").forEach((l) => (l.style.visibility = ""));
    const on = ui.rulerTicks.querySelector('.ruler-tick[data-v="' + mode.target + '"] .lbl');
    if (on) on.style.visibility = "hidden";
  }
  if (ui.rulerFill) {
    if (mode.direction === "under") {
      ui.rulerFill.style.bottom = "0%";
      ui.rulerFill.style.height = mode.target + "%";
    } else {
      ui.rulerFill.style.bottom = mode.target + "%";
      ui.rulerFill.style.height = 100 - mode.target + "%";
    }
  }
  if (ui.resultMarker) ui.resultMarker.hidden = true;
}

// Slide the result marker to the rolled value; green if it lands in the win zone.
function showResult(roll, isWin) {
  const rm = ui.resultMarker;
  if (!rm) return;
  rm.hidden = false;
  rm.className = "ruler-marker result " + (isWin ? "win" : "loss") + " enter";
  rm.style.bottom = Math.max(0, Math.min(100, roll)) + "%";
  rm.querySelector(".val").textContent = roll.toFixed(2);
  rm.addEventListener("animationend", () => rm.classList.remove("enter"), { once: true });
}

function updateUI() {
  const mode = currentMode();
  if (!mode) return;
  const betCurrency = betUnits();

  state.target = mode.target;
  ui.chanceSlider.value = String(mode.target);
  ui.chanceLabel.textContent = mode.winChance + "%";
  ui.targetText.textContent = "Target " + mode.target;
  ui.multiplier.value = mode.multiplier.toFixed(2);
  ui.statMultiplier.textContent = mode.multiplier.toFixed(2) + "×";
  ui.statChance.textContent = mode.winChance + "%";
  ui.statPayout.textContent = fmtMoney(betCurrency * mode.multiplier);

  ui.underBtn.classList.toggle("active", state.direction === "under");
  ui.overBtn.classList.toggle("active", state.direction === "over");

  // Ape rests on the target line; the ruler is the primary indicator.
  if (ui.stage) ui.stage.dataset.dir = mode.direction; // drives the red/green --dir accent
  els.monkey.style.bottom = heightPct(mode.target) + "%";
  paintWinZone(mode);
  paintRuler(mode);
}

function applySliderRange() {
  const r = state.ranges[state.direction];
  ui.chanceSlider.min = String(r.min);
  ui.chanceSlider.max = String(r.max);
  ui.chanceSlider.step = "1";
}

function setDirection(direction) {
  state.direction = direction;
  state.target = clampTarget(direction, state.target);
  applySliderRange();
  updateUI();
}

function setModeBadge() {
  if (!ui.modeBadge) return;
  ui.modeBadge.textContent = IS_LIVE ? "LIVE RGS" : "LOCAL REPLAY";
  ui.modeBadge.dataset.mode = IS_LIVE ? "live" : "local";
}

// ---- data + init ------------------------------------------------------------
async function loadBundle() {
  const res = await fetch(DATA_URL);
  if (!res.ok) throw new Error(`data HTTP ${res.status}`);
  const data = await res.json();
  if (!data?.modes?.length) throw new Error("empty data bundle");
  state.modesByName = {};
  const range = { under: { min: Infinity, max: -Infinity }, over: { min: Infinity, max: -Infinity } };
  for (const m of data.modes) {
    state.modesByName[m.name] = m;
    const r = range[m.direction];
    if (r) {
      r.min = Math.min(r.min, m.target);
      r.max = Math.max(r.max, m.target);
    }
  }
  for (const d of ["under", "over"]) {
    if (Number.isFinite(range[d].min)) state.ranges[d] = range[d];
  }
}

function applyLaunchMode() {
  const m = LAUNCH_MODE && state.modesByName[LAUNCH_MODE];
  if (m) {
    state.direction = m.direction;
    state.target = m.target;
  } else {
    state.direction = "under";
    state.target = clampTarget("under", 50);
  }
}

async function init() {
  state.currency = CURRENCY;
  ui.balanceText.textContent = "Balance —";
  setModeBadge();

  try {
    await loadBundle();
  } catch (err) {
    console.error(err);
    showToast("Could not load math data (run build_demo_data.py + serve over http).", "loss");
    return;
  }

  applyLaunchMode();
  applySliderRange();
  buildRuler();
  ui.chanceSlider.value = String(state.target);

  ui.chanceSlider.addEventListener("input", (e) => {
    state.target = clampTarget(state.direction, Number(e.target.value));
    updateUI();
  });
  ui.betAmount.addEventListener("input", () => {
    state.bet = toApi(Math.max(0, Number(ui.betAmount.value || 0)));
    updateUI();
  });
  ui.betMinus.addEventListener("click", () => nudgeBet("minus"));
  ui.betPlus.addEventListener("click", () => nudgeBet("plus"));
  ui.autoBetsMinus.addEventListener("click", () => nudgeAutoBets(-1));
  ui.autoBetsPlus.addEventListener("click", () => nudgeAutoBets(1));
  ui.autoStopProfitMinus.addEventListener("click", () => nudgeStop(ui.autoStopProfit, -1));
  ui.autoStopProfitPlus.addEventListener("click", () => nudgeStop(ui.autoStopProfit, 1));
  ui.autoStopLossMinus.addEventListener("click", () => nudgeStop(ui.autoStopLoss, -1));
  ui.autoStopLossPlus.addEventListener("click", () => nudgeStop(ui.autoStopLoss, 1));
  ui.underBtn.addEventListener("click", () => setDirection("under"));
  ui.overBtn.addEventListener("click", () => setDirection("over"));
  ui.rollBtn.addEventListener("click", () => rollDice());
  wireMonkeyDrag();

  // Autobet: tabs, toggles, and the START/STOP button.
  ui.manualTab.addEventListener("click", () => setAutoTab(false));
  ui.autoTab.addEventListener("click", () => setAutoTab(true));
  ui.autoInfinite.addEventListener("click", () => ui.autoInfinite.classList.toggle("active"));
  ui.autoFast.addEventListener("click", () => ui.autoFast.classList.toggle("active"));
  const segPair = (resetBtn, incBtn, field) => {
    const sync = (isReset) => field.classList.toggle("is-reset", isReset);
    resetBtn.addEventListener("click", () => { resetBtn.classList.add("active"); incBtn.classList.remove("active"); sync(true); });
    incBtn.addEventListener("click", () => { incBtn.classList.add("active"); resetBtn.classList.remove("active"); sync(false); });
    sync(resetBtn.classList.contains("active")); // Reset active by default -> dimmed
  };
  segPair(ui.autoWinReset, ui.autoWinInc, ui.autoWinField);
  segPair(ui.autoLossReset, ui.autoLossInc, ui.autoLossField);

  // Percent steppers (− / +): jump by 10, clamp 0..500; typing is clamped on change.
  const PCT_STEP = 10, clampPct = (n) => Math.max(0, Math.min(500, Math.round(Number(n) || 0)));
  const nudgePct = (input, dir) => {
    input.value = String(clampPct((Number(input.value) || 0) + dir * PCT_STEP));
    input.dispatchEvent(new Event("input", { bubbles: true }));
  };
  ui.autoWinMinus.addEventListener("click", () => nudgePct(ui.autoWinPct, -1));
  ui.autoWinPlus.addEventListener("click", () => nudgePct(ui.autoWinPct, +1));
  ui.autoLossMinus.addEventListener("click", () => nudgePct(ui.autoLossPct, -1));
  ui.autoLossPlus.addEventListener("click", () => nudgePct(ui.autoLossPct, +1));
  [ui.autoWinPct, ui.autoLossPct].forEach((inp) =>
    inp.addEventListener("change", () => { inp.value = String(clampPct(inp.value)); })
  );
  ui.autoBtn.addEventListener("click", () => {
    if (state.auto.running) {
      state.auto.stopRequested = true;
      ui.autoBtn.textContent = "STOPPING…";
    } else {
      startAutobet();
    }
  });

  try {
    const resp = IS_LIVE ? await liveAuth() : localAuth();
    state.currency = resp.balance?.currency || CURRENCY;
    setBalanceApi(resp.balance?.amount ?? 0);
    if (IS_LIVE) {
      state.betLevels = resp.config || null;
      state.bet = snapLiveBet(resp.config?.defaultBetLevel || API_MULTIPLIER);
      ui.betAmount.value = betUnits().toFixed(2);
    } else {
      state.bet = toApi(Math.max(0, Number(ui.betAmount.value || 10)));
    }
    if (IS_LIVE && resp.round && resp.round.active === true) state.hasOpenRound = true;
  } catch (err) {
    console.error(err);
    showToast("Could not authenticate with the RGS — using LOCAL replay.", "loss");
  }

  updateUI();
}

// ---- drag the ape to pick a target ------------------------------------------
function wireMonkeyDrag() {
  let dragging = false;
  const setFromPointer = (clientY) => {
    const tower = document.querySelector(".tower");
    const rect = tower.getBoundingClientRect();
    // invert heightPct: dice value from the pointer's height over the stage.
    const stage = document.querySelector(".game-stage").getBoundingClientRect();
    const bottomPct = ((stage.bottom - clientY) / stage.height) * 100;
    const v = ((bottomPct - AXIS_BOTTOM) / AXIS_SPAN) * 100;
    state.target = clampTarget(state.direction, v);
    updateUI();
  };
  els.monkey.addEventListener("pointerdown", (e) => {
    if (state.rolling) return;
    dragging = true;
    els.monkey.classList.add("dragging");
    els.monkey.setPointerCapture(e.pointerId);
    setFromPointer(e.clientY);
  });
  els.monkey.addEventListener("pointermove", (e) => {
    if (dragging && !state.rolling) setFromPointer(e.clientY);
  });
  const stop = (e) => {
    if (!dragging) return;
    dragging = false;
    els.monkey.classList.remove("dragging");
    if (e.pointerId !== undefined && els.monkey.hasPointerCapture(e.pointerId)) {
      els.monkey.releasePointerCapture(e.pointerId);
    }
  };
  els.monkey.addEventListener("pointerup", stop);
  els.monkey.addEventListener("pointercancel", stop);
}

init();
